---
name: create-labels

on:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: micnncim/action-label-syncer@30a4ae8eee2f8092fa780519c430cae0ba1fc087
        with:
          manifest: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
