---
name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@e0621940a8f3b9653ad63ca7162fd08f7bdcc5cf
        env:
          MERGE_METHOD: squash
          MERGE_LABELS: automerge,!WIP
          MERGE_COMMIT_MESSAGE: pull-request-title
          UPDATE_METHOD: rebase
          UPDATE_LABELS: autorebase
          GITHUB_TOKEN: ${{ secrets.KUBEES_TOKEN }}
